### ISSUE TITLE
Validator.php returns undefined method error.

### ISSUE THREAD

**Issue by jonmoss** [castlegateit/cgit-wp-postman#1]
On form submission:

Fatal error: Call to undefined method Cgit\Postman\Validator::() in \plugins\cgit-wp-postman-master\src\Cgit\Postman\Validator.php on line 70.

I also get a warning:

Warning: ucwords() expects exactly 1 parameter, 2 given in \plugins\cgit-wp-postman-master\src\Cgit\Postman\Validator.php on line 105

**Comment by johnkhughes** [comment]
Can you let me know which PHP version you are using?

**Comment by jonmoss** [comment]
5.5.12 on my local install of Wamp.

**Comment by jonmoss** [comment]
Can confirm error does not occur on PHP 5.6.15.
