### ISSUE TITLE
Downloaded files cached by proxies

### ISSUE THREAD

**Issue by ajreading** [castlegateit/cgit-wp-postman#10]
When using a proxy, cache, CDN, or load balancer such as Cloudflare , files which would otherwise by password protected are cached and can therefore be accessed without credentials so long as the cached version exists.

Cache control headers must be sent when delivering a protected file. 

`Cache-Control "private"`

**Comment by johnkhughes** [comment]
Which downloads should be protected here?

**Comment by ajreading** [comment]
In this case, the CSV downloads require the header

**Comment by johnkhughes** [comment]
Header added in 2.8.
