### ISSUE TITLE
Feature request: Log deletion and purging

### ISSUE THREAD

**Issue by ajreading** [castlegateit/cgit-wp-postman#11]
The plugin requires the ability to delete log entries. This should allow for deletion of single or multiple (all) entries.

An additional purge feature will help protect against storing personal information indefinitely. I'd suggest 1 year retention as a starting point, with the ability to filter the value. Purging could happen automatically via WordPress cron. It would be beneficial to present the user with the option to purge manually using a range of predefined time-frames such as "last day, last week, last month, 3 months, 6 months, 1 year" etc

**Comment by johnkhughes** [comment]
I have added some buttons to the tools menu for deleting logs manually and I have added some constants that will delete logs automatically on admin page requests.
