### ISSUE TITLE
Validation rule specific error messages.

### ISSUE THREAD

**Issue by rjackson** [castlegateit/cgit-wp-postman#4]
If a field fails the `required` rule I'd like to yell at the user with "Oi, that's required."

If if fails the `'type' => 'email'` rule I'd like to yell "Your e-mail sucks".

Currently this is not possible.

**Comment by johnkhughes** [comment]
I thought that was possible. It's implemented like that in Postcard, isn't it?

**Comment by johnkhughes** [comment]
Feature added in v2.8. Check out the README.
