### ISSUE TITLE
Feature Request: Field-specific Columns

### ISSUE THREAD

**Issue by jonmoss** [castlegateit/cgit-wp-postman#7]
For the purpose of providing easily-manipulable CSV exports to customers, which is apparently a standard feature, we should have Postman log to the database in a one-field one-column structure, rather than throwing everything into one.

Alternatively we can use the Log Spooler to parse the field_data column?

**Comment by johnkhughes** [comment]
The plugin has to create the database tables on activation and forms can have any number of different fields, so we can't have the database tables columns match the form fields, hence the JSON encoding of the data. But the built-in log download should convert it back into CSV columns. Are you saying that isn't working?

**Comment by jonmoss** [comment]
I've just tested and the CSV seems to work fine. The issue is superfluous - sorry!
