### ISSUE TITLE
Debug Functions

### ISSUE THREAD

**Issue by jonmoss** [castlegateit/cgit-wp-postman#9]
As discussed at our conference recently, could we integrate into Postman some more thorough debugging tools/logic, so we can query where in the plugin logic a form submission reached before failing, what data the form is holding and what validation has run?

It's currently quite difficult to debug a failing Postman submission without directly inserting var_dump() statements or exceptions into the plugin itself, which we should avoid.

I'm happy to do this myself if nobody bites.

**Comment by johnkhughes** [comment]
Nobody has bitten :)

**Comment by jonmoss** [comment]
You can access this data by simply dumping the Postman object. Alternatively, using an IDE with proper debugging support makes doing this trivial using breakpoints, so since nobody else has expressed much interest in this feature, I'll close the issue.
